In [1]:
a = 1
b = 2
c = a + b 
print(c)

3


Expected: 0,1,2 (hvorfor ikke 2 her også?) and 2,3,4,5

In [2]:
x=[0,1,2,3,4,5]
print(x[:2])
print(x[2:])

[0, 1]
[2, 3, 4, 5]


In [3]:
x = [1,2,3]
y=x
y[-1] = 4
print(x)

[1, 2, 4]


Loops - break

In [6]:
for i in range(5):
    if i >= 2: break
    print(i)

0
1


Loops - continue (hvad betyder ==?)

In [7]:
for i in range(5):
    if i == 2: continue
    print(i)

0
1
3
4


In [8]:
x = 3
if x > 3:
    print('too big')
elif x < 1:
    print('too small')
else:
    print('just right')

just right


In [9]:
#functions and scope:
def f(x):
    return x+a # a is a global variable
def g(x, a=1):
    return x+a #a is local variable here
print(f(1))
print(g(1))
a = 2
print (f(1))
print (g(1))

2
2
3
2


In [1]:
# numpy 
import numpy as np
x = np.array([1,2,3])
y = x
x += 1
print(y)
x[:] = x+1 
print(y)
x = x + 1 
print(y)


[2 3 4]
[3 4 5]
[3 4 5]


In [17]:
# classes
class SquareClass:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def size(self):
        return self.length * self.width

square = SquareClass(2, 2)
print(square.size())

4


In [2]:
import numpy as np
x = np.array([2, 5, 10, 2, 4])






